stages:
  train_burger:
    cmd: python script_training/training_burger.py
    deps:
    - pinn_loss/
    - script_training/training_burger
    outs:
    - models_params/model_gnn.json
  eval_burger:
    cmd: python script_training/training_burger.py --mode eval
    deps:
    - models_params/model_gnn.json
    - pinn_loss/
    - script_training/training_burger
    outs:
    - plots/results.png
