stages:
  train_burger:
    cmd: python3 script_training/training_burger.py
    deps:
    - pinn_loss/
    - script_training/training_burger.py
    outs:
    - models_params/model_gnn.json
  eval_burger:
    cmd: script_training/training_burger.py -o plots/ -M metrics/metrics_random_sample.json
      -M metrics/metrics.json python3 script_training/training_burger.py --mode eval
    deps:
    - models_params/model_gnn.json
    - pinn_loss/
