stages:
  train_burger:
    cmd: python3 -m script_training/training_burger.py
    deps:
    - pinn_loss/
    - script_training/training_burger.py
    outs:
    - models_params/model_gnn.json
  eval_burger:
    cmd: python3 -m script_training/eval_burger.py
    deps:
    - models_params/model_gnn.json
    - pinn_loss/
    - script_training/eval_burger.py
    metrics:
    - metrics/metrics_burger.json:
        cache: false
