stages:
  train:
    cmd: python3 script_training/training_burger.py
    deps:
    - script_training/training_burger.py
    outs:
    - models_params/model_gnn.json
  eval:
    cmd: python script_training/training_burger.py --mode eval
    deps:
    - models_params/model_gnn.json
    - script_training/training_burger.py
    metrics:
    - metrics/metrics.json:
        cache: false
    - metrics/metrics_random_sample.json:
        cache: false
